name: Build FFmpeg for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # または ubuntu-24.04 に変更可能
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            autoconf automake build-essential cmake libtool git \
            pkg-config texinfo nasm yasm curl \
            libssl-dev libmp3lame-dev zlib1g-dev libfdk-aac-dev mingw-w64

sudo apt-get update
          sudo apt-get install -y \
            autoconf automake build-essential cmake libtool git \
            pkg-config texinfo nasm yasm curl \
            mingw-w64 g++-mingw-w64-x86-64 \
            libssl-dev libmp3lame-dev zlib1g-dev libfdk-aac-dev \
            libass-dev libbluray-dev libbs2b-dev libcaca-dev \
            libopencore-amrnb-dev libopencore-amrwb-dev libopus-dev \
            libspeex-dev libtheora-dev libvidstab-dev \
            libvo-amrwbenc-dev libvorbis-dev libvpx-dev libx264-dev libxvidcore-dev

      - name: Build OpenSSL for Windows
        run: |
          git clone https://github.com/openssl/openssl.git
          cd openssl
          git checkout tags/openssl-3.5.2
          export CROSS_COMPILE=x86_64-w64-mingw32-
          ./Configure mingw64 no-shared --cross-compile-prefix=$CROSS_COMPILE --prefix=$HOME/openssl-win
          make -j$(nproc)
          make install_sw

      - name: Build LAME for Windows
        run: |
          git clone https://github.com/rbrito/lame.git
          cd lame
          ./configure \
          --host=x86_64-w64-mingw32 \
          --disable-shared \
          --enable-static \
          --prefix=$HOME/lame-win
          make -j$(nproc)
          make install

      - name: Clone FFmpeg
        run: |
          git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
          cd ffmpeg
          git checkout tags/n8.0  # 任意の安定版に変更可能

      - name: Configure FFmpeg for Windows (x86_64)
        run: |
          cd ffmpeg
          ./configure \
          --cross-prefix=x86_64-w64-mingw32- \
          --enable-cross-compile \
          --arch=x86_64 \
          --target-os=mingw32 \
          --prefix=/opt/mxe/usr/x86_64-w64-mingw32.static \
          --enable-static --disable-shared \
          --yasmexe=x86_64-w64-mingw32.static-yasm \
          --disable-debug \
          --disable-pthreads \
          --enable-w32threads \
          --disable-doc \
          --enable-gpl \
          --enable-version3 \
          --extra-libs=-mconsole \
          --enable-gnutls \
          --enable-libass \
          --enable-libbluray \
          --enable-libbs2b \
          --enable-libcaca \
          --enable-libmp3lame \
          --enable-libopencore-amrnb \
          --enable-libopencore-amrwb \
          --enable-libopus \
          --enable-libspeex \
          --enable-libtheora \
          --enable-libvidstab \
          --enable-libvo-amrwbenc \
          --enable-libvorbis \
          --enable-libvpx \
          --enable-libx264 \
          --enable-libxvid \
          --extra-ldflags=-fstack-protector
#          --enable-libmp3lame \

      - name: Build FFmpeg
        run: |
          cd ffmpeg
          make -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-windows-build
          path: ffmpeg/ffmpeg.exe
