name: Build FFmpeg ubuntu Static

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ubuntu:
          - "22.04"
          - "24.04"
          - "26.04"

    runs-on: ubuntu-${{ matrix.ubuntu }}

    env:
      FFMPEG_VERSION: "9.0.2"
      LAME_VERSION: "3.100"

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            autoconf automake build-essential cmake libtool git \
            pkg-config texinfo nasm yasm \
            libssl-dev libmp3lame-dev zlib1g-dev libfdk-aac-dev

      - name: Fix LAME pkg-config
        run: |
          MULTIARCH="$(dpkg-architecture -qDEB_HOST_MULTIARCH)"
          PKGCONFIG_DIR="/usr/lib/$MULTIARCH/pkgconfig"

          if [ -f "$PKGCONFIG_DIR/lame.pc" ] &&
             [ ! -f "$PKGCONFIG_DIR/libmp3lame.pc" ]; then
            sudo ln -s lame.pc "$PKGCONFIG_DIR/libmp3lame.pc"

          pkg-config --modversion libmp3lame

          fi
          
      - name: Build FFmpeg
        run: |
          wget https://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.gz
          tar -xzf ffmpeg-${FFMPEG_VERSION}.tar.gz

          cd ffmpeg-${FFMPEG_VERSION}

          ./configure \
            --prefix="$HOME/ffmpeg-static" \
            --pkg-config-flags="--static" \
            --extra-cflags="-static -I/usr/include" \
            --extra-ldflags="-static -L/usr/lib" \
            --enable-gpl \
            --enable-nonfree \
            --enable-libmp3lame \
            --enable-libfdk-aac \
            --enable-encoder=png,jpeg \
            --enable-openssl \
            --enable-protocol=https \
            --enable-protocol=hls \
            --disable-shared \
            --enable-static \
            --disable-debug \
            --disable-doc

          make -j"$(nproc)"
          make install

      - name: Prepare artifact
        run: |
          mkdir -p "ffmpeg-${{ matrix.ubuntu }}"
          cp "$HOME/ffmpeg-static/bin/ffmpeg" \
             "ffmpeg-${{ matrix.ubuntu }}/ffmpeg"

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-${{ matrix.ubuntu }}
          path: ffmpeg-${{ matrix.ubuntu }}

  package:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Ubuntu 22.04
        uses: actions/download-artifact@v4
        with:
          name: ffmpeg-22.04
          path: ffmpeg-static/ubuntu-22.04

      - name: Download Ubuntu 24.04
        uses: actions/download-artifact@v4
        with:
          name: ffmpeg-24.04
          path: ffmpeg-static/ubuntu-24.04

      - name: Download Ubuntu 26.04
        uses: actions/download-artifact@v4
        with:
          name: ffmpeg-26.04
          path: ffmpeg-static/ubuntu-26.04

      - name: Upload combined artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-static
          path: ffmpeg-static
