name: Build FFmpeg for Windows

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf automake build-essential cmake git libtool pkg-config \
          yasm nasm \
          mingw-w64

    - name: Clone FFmpeg
      run: |
        git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
        cd ffmpeg
        git checkout release/6.0  # 任意の安定版に変更可能

    - name: Configure FFmpeg for Windows (x86_64)
      run: |
        cd ffmpeg
        ./configure \
          --target-os=mingw32 \
          --arch=x86_64 \
          --cross-prefix=x86_64-w64-mingw32- \
          --enable-gpl \
          --enable-version3 \
          --enable-static \
          --disable-shared \
          --disable-debug \
          --disable-doc \
          --enable-libx264 \
          --enable-libx265 \
          --enable-libvpx \
          --enable-libopus \
          --enable-libmp3lame \
          --enable-libvorbis

    - name: Build FFmpeg
      run: |
        cd ffmpeg
        make -j$(nproc)

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ffmpeg-windows-build
        path: ffmpeg/ffmpeg.exe
