name: Build mxe FFmpeg for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # または ubuntu-24.04 に変更可能
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential autoconf automake autopoint \
            bash bison bzip2 ca-certificates cmake curl flex g++ g++-multilib \
            gettext git gperf intltool lzip make openssl patch perl p7zip-full python-is-python3 \
            python3 python3-mako python3-packaging python3-pip python3-pkg-resources python3-setuptools \
            unzip wget xz-utils
            pip3 install mako

      - name: Clone FFmpeg
        run: |
          git clone https://github.com/mxe/mxe.git 
          cd mxe 
          make MXE_TARGETS='x86_64-w64-mingw32.static' ffmpeg -j$(nproc)

      - name: Build FFmpeg
        run: |
          cd ffmpeg
          make -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-windows-build
          path: ffmpeg/ffmpeg.exe
