name: Build static FFmpeg (glibc)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      PREFIX: ${{ github.workspace }}/ffmpeg-static
      DEPS: ${{ github.workspace }}/deps

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            yasm nasm pkg-config build-essential \
            autoconf automake libtool \
            zlib1g-dev curl

      - name: Prepare directories
        run: |
          mkdir -p "$DEPS" "$PREFIX"

      - name: Build libmp3lame
        run: |
          cd "$DEPS"
          curl -LO https://downloads.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz
          tar xzf lame-3.100.tar.gz
          cd lame-3.100
          ./configure --prefix="$DEPS/lame" --enable-nasm --disable-shared --enable-static
          make -j$(nproc)
          make install

      - name: Build OpenSSL
        run: |
          cd "$DEPS"
          curl -LO https://www.openssl.org/source/openssl-1.1.1w.tar.gz
          tar xzf openssl-1.1.1w.tar.gz
          cd openssl-1.1.1w
          ./Configure linux-x86_64 no-shared --prefix="$DEPS/openssl"
          make -j$(nproc)
          make install_sw

      - name: Build FFmpeg
        run: |
          cd "$GITHUB_WORKSPACE"
          git clone https://github.com/FFmpeg/FFmpeg.git
          cd FFmpeg
          ./configure \
            --prefix="$PREFIX" \
            --pkg-config-flags="--static" \
            --extra-cflags="-I$DEPS/lame/include -I$DEPS/openssl/include" \
            --extra-ldflags="-L$DEPS/lame/lib -L$DEPS/openssl/lib -static" \
            --extra-libs="-lssl -lcrypto -lz" \
            --enable-gpl \
            --enable-nonfree \
            --enable-libmp3lame \
            --enable-openssl \
            --enable-protocol=https \
            --enable-protocol=hls \
            --disable-shared \
            --enable-static \
            --disable-debug \
            --disable-doc
          make -j$(nproc)
          make install

      - name: Upload FFmpeg binary
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-static
          path: ${{ env.PREFIX }}/bin/ffmpeg