name: Create Universal FFmpeg for macOS

on:
  workflow_dispatch:

jobs:
  create-universal-ffmpeg:
    runs-on: macos-latest

    steps:
      - name: Set up tools
        run: |
          brew install p7zip

      - name: Download FFmpeg ARM (Apple Silicon)
        run: |
          wget -qO ffmpeg-arm.zip https://www.osxexperts.net/ffmpeg80arm.zip || { echo "Failed to download arm FFmpeg"; exit 1; }
          unzip ffmpeg-arm.zip -d arm
          mv arm/ffmpeg ffmpeg-arm
          chmod +x ffmpeg-arm

      - name: Download FFmpeg Intel (x86_64)
        run: |
          wget -qO ffmpeg-intel.7z https://evermeet.cx/ffmpeg/ffmpeg-8.0.7z || { echo "Failed to download FFmpeg-intel"; exit 1; }
          7z x ffmpeg-intel.7z -offmpeg-intel
          mv ffmpeg-intel/ffmpeg ffmpeg-x86_64
          chmod +x ffmpeg-x86_64

      - name: Verify architectures
        run: |
          lipo -info ffmpeg-arm
          lipo -info ffmpeg-x86_64

      - name: Create Universal Binary
        run: |
          lipo -create ffmpeg-arm ffmpeg-x86_64 -output ffmpeg
          chmod +x ffmpeg
          lipo -info ffmpeg

      - name: Archive universal binary
        run: |
          tar -czf ffmpeg-macos-universal.tar.gz ffmpeg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-macos-universal
          path: ffmpeg-macos-universal.tar.gz
