name: Build FFmpeg for Android

on:
  workflow_dispatch:

jobs:
  build-ffmpeg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t ffmpeg-android .

      - name: Run container
        run: |
          docker run -d --name ffmpeg-container ffmpeg-android tail -f /dev/null

      - name: Copy artifact
        run: |
          docker cp ffmpeg-container:/ffmpeg/android/arm ./output
          docker rm -f ffmpeg-container

      - name: Upload FFmpeg Android build
        uses: actions/upload-artifact@v4
        with:
           name: ffmpeg-android-build
           path: output/
