name: Build FFmpeg ubuntu Static

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04-arm  # または ubuntu-24.04 に変更可能
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            autoconf automake build-essential cmake libtool git \
            pkg-config texinfo nasm yasm \
            libssl-dev libmp3lame-dev zlib1g-dev libfdk-aac-dev

      - name: Clone FFmpeg
        run: |
          git clone https://github.com/FFmpeg/FFmpeg.git ffmpeg
          cd ffmpeg
          git checkout tags/n7.1.1
          ./configure \
            --prefix=$HOME/ffmpeg-static \
            --pkg-config-flags="--static" \
            --extra-cflags="-static -I/usr/include" \
            --extra-ldflags="-static -L/usr/lib" \
            --enable-gpl \
            --enable-nonfree \
            --enable-libmp3lame \
            --enable-libfdk-aac \
            --enable-encoder=png,jpeg \
            --enable-openssl \
            --enable-protocol=https \
            --enable-protocol=hls \
            --disable-shared \
            --enable-static \
            --disable-debug \
            --disable-doc
          make -j$(nproc)
          make install

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-static
          path: ~/ffmpeg-static/bin
